version: '3.8'
services:
    timescaledb:
        image: timescale/timescaledb-ha:pg15-latest
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=postgres
            - WAL_LEVEL=logical
        command: postgres -c wal_level=logical
